### ISSUE TITLE
Consistency issue using aetest

### ISSUE THREAD

**Issue by zboralski** [mjibson/goon#41]
If I try to create an entity in a unit test :

```
	u := &User{Name: "Joe", CName: "joe"}
	k, err := n.Put(u)
	if err != nil {
		t.Fatal(err)
	}
```

Parentless queries will fail because of a consistency issue (parentless puts may not be available right away.)

The problem can be avoided by sleeping for 1 second but the test becomes dependent on the machine load, etc.
```
	// Sleep a bit to wait for the HRD emulation to get out of our way
	time.Sleep(1000 * time.Millisecond)
```

According to this [post](https://groups.google.com/d/msg/google-appengine-go/Fibzx-9p3zU/20BEFJiMQdoJ) the proper way to avoid this issue inside a test is to get the entity using its known key, right after.

My subsequent queries work perfectly if I perform a `datastore.Get(c,k,u)` first.

However they fail miserably if I use `n.Get(u)` even though the key is known and set:

**Comment by zboralski** [comment]
@mzimmerman gets coming in the next request after a write fail all the time... that's in an app not a test.

Also @xStrom flushing the local cache before every get really defeats the purpose of having a local cache...

**Comment by xStrom** [comment]
It's important that we remember the scope of the conversation - which is unit tests. I suggested using ```FlushLocalCache``` precisely because the local cache was getting in your way. However if you have a different goal, where you want to use the local cache, then of course flushing it works against your goal.

**Comment by mzimmerman** [comment]
Yes, this is not a goon issue.  What you're essentially now asking for is the goon.Get() function to go back to the datastore when the key is already in the cache.  If we did that, goon would really be failing in it's mission.

In your tests, when you need to query results of an entity, do the following.
```go
datastore.Get(c,g.Key(data),data)
```
Then continue on in your tests as normal.  This does not destroy the local cache.  Note that if you're having this issue in your tests, you'll also have it in production.  Datastore queries are *eventual* consistency, not immediate -- this is regardless of using goon.
