### ISSUE TITLE
Can code depending on goon be unit tested without devserver?

### ISSUE THREAD

**Issue by gabrielf** [mjibson/goon#52]
Hi, I'd like to unit test my code that relies on datastore in a way that does not require the devserver to be started. Is it possible to use goon and test without it using aetest and starting a devserver behind the covers?

**Comment by mjibson** [comment]
I don't think that's possible. What would be emulating the data store in
that case?

**Comment by gabrielf** [comment]
An in memory implementation I guess. Now that I write it out I realise that it would be quite cumbersome to emulate all of the eventual consistency aspects of datastore and I guess it would be a better bet to do the mocking at a higher level.

Thanks for the quick response!
