### ISSUE TITLE
Changes by PropertyLoadSaver.Load aren't cached.

### ISSUE THREAD

**Issue by lacolaco** [mjibson/goon#53]
Currently, goon.Get calls methods as below
.. => goon.Get => datastore.Get => goon.putMemcache => ..
or (if it's cached)
.. => goon.Get => memcache.Get => goon.putMemcache => ..

I think this flow has a problem.
PropertyLoadSaver.Load is called in only datastore.Get.
And goon.putMemcache ignores fields which tagged as `datastore:"-"`.
Therefore the fields changed by PropertyLoadSaver.Load aren't cached.

The return of goon.Get should be same whether it's cached or not.

**Comment by laco0416** [comment]
I have another idea;  `GoonLoadSaver` may be able to solve this issue.

GoonLoadSaver.Save is called after g.Put before datastore/mamcache.Put.

 > g.Put(sample) => sample.OnGoonSave() => datastore.Put => .. 

GoonLoadSaver.Load is called after g.putMemcache.
 > g.Get(sample) => datastore.Get => g.putMemcache(sample) => sample.OnGoonLoad() =>  ..

example:

```go
type GoonLoadSaver interface {
  OnGoonLoad(c context.Context) error
  OnGoonSave(c context.Context) error
}

func (s *Sample) OnGoonLoad(c context.Context) error {
  return nil
}

func (s *Sample) OnGoonSave(c context.Context) error {
  return nil
}
```

If GoonLoadSaver comes out, I can use it instead of PropertyLoadSaver.

**Comment by vvakame** [comment]
:+1:

**Comment by mjibson** [comment]
Sounds great. Submit a PR and I'll review it.

**Comment by curuknagao** [comment]
i want goon loadsaver interface and found this issue.
has goon loadsaver interface already included?

**Comment by xStrom** [comment]
Not yet I'm afraid. You can track its progress in #69.
