### ISSUE TITLE
Using context.Context in place of *http.Request

### ISSUE THREAD

**Issue by johngb** [mjibson/goon#55]
I noticed that goon uses a `*http.Request` instead of a `context.Context` when creating a `*Goon`, which is only used to get a new `context.Context`. I'm not clear on the reasoning behind this decision as it breaks from the common Go and AppEngine style of passing in a context.Context as the first argument in a function call.  Especially since the vast majority of functions will already have a `context.Context`, but it's usually only the handler function which has a `*http.Request` to pass in.

I would suggest requiring a `context.Context` as the argument instead of the `*http.Request` which is currently used.  However I'd love to get some feedback on this.

**Comment by mjibson** [comment]
https://godoc.org/github.com/mjibson/goon#FromContext

**Comment by johngb** [comment]
Clearly I missed that.

As this is the typical way of doing things in AppEngine, might I suggest that the docs use FromContext in the examples rather than NewGoon.

**Comment by mjibson** [comment]
Good suggestion. I've opened an issue to track that.

**Comment by mzimmerman** [comment]
In goon's defense, the API and corresponding documentation were written
before context.Context existed.

**Comment by johngb** [comment]
@mzimmerman I assumed as much.  I've had enough of my own issues having to update everything to the context.Context package, so I completely understand goon using the request, which would have been the most logical solution back then.
