### ISSUE TITLE
GetMulti and Get don't ignore field mismatch in Tx

### ISSUE THREAD

**Issue by shota-takahashi-tg** [mjibson/goon#70]
Hello,
Thank you a lot for this package. it is always a great help for us.

By the way, I encountered its behavior as this Title, when I try to use the new function `IgnoreFieldMismatch` .
https://github.com/mjibson/goon/commit/a3e1c6182761ea1bc1bf23224ddc501743c2c633#diff-fd6485aca5f3b9fb50a56fbfc9f202b4R414

I think It's better to be improved, If it is not by design.

Thanks again

**Comment by xStrom** [comment]
Thank you for the report! I agree that this needs to be improved. I will try to do it this weekend.

**Comment by xStrom** [comment]
Sorry for the delay. I have now written a patch to fix this issue.
