### ISSUE TITLE
Request: Add release tag for go modules

### ISSUE THREAD

**Issue by ryo-yamaoka** [mjibson/goon#86]
https://github.com/golang/go/wiki/Modules#modules

This repository has no tag.
I think we should add a semver tag for go modules.
We can use only commit hash designate now, It is inconvenient.

**Comment by xStrom** [comment]
Thanks for the suggestion! I need to do a bit of thinking (and reading) about what version number to start with because we have a legacy v1 branch already. I will get this done before the end of May, hopefully sooner than later.

**Comment by xStrom** [comment]
[Version 1.0.0](https://github.com/mjibson/goon/releases/tag/v1.0.0) has been released and it includes [full modules support](https://github.com/mjibson/goon/pull/92).

**Comment by ryo-yamaoka** [comment]
Thanks!
